### ISSUE TITLE
NotImplementedError: Force plate data not supported.

### ISSUE THREAD

**Issue by lkumar93** [crigroup/optitrack#3]
Hello ,

I am trying to use the optitrack that is connected to a windows machine through motive 1.7.5 and stream data to a linux machine. I tried running this package after making sure all the settings are correct. However it gives out an NotImplementedError : Force plate data not supported. Any help would be greatly appreciated. I am using ROS Indigo and Ubuntu 14.04

**Comment by fsuarez6** [comment]
The error you mention is given by the `python-optirx` module (See [here](https://bitbucket.org/astanin/python-optirx/src/089ff9363c8ba9f547b8ffa34f13f153763c72b8/optirx.py?at=master&fileviewer=file-view-default#optirx.py-304)). 
Could you please give more details about your setup? (Cameras, markers, rigid bodies, etc...)

**Comment by lkumar93** [comment]
4 Cameras (Optitrack Prime 17W) , 3 Markers, 1 Rigid Body

**Comment by fsuarez6** [comment]
Did you manage to solve this issue?

**Comment by EpiCabbage** [comment]
Hi, the problem is caused by mismatch of SDK version.

Firstly, check the version of your Motive SDK: go to Help -> About Motive .. -> NatNet Streaming Module
for our Motive, it's 2.7.0.0

Then, edit rigid_body_publisher.py from the optitrack package:
change the line:
**version = (2, 9, 0, 0)  # the latest SDK version**
to
**version = (2, 7, 0, 0)**

Hope this helps.
